# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dot < Formula
  desc "Type-safe symbolic link manager for dotfiles"
  homepage "https://github.com/yaklabco/dot"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/dot/releases/download/v0.6.6/dot_0.6.6_Darwin_x86_64.tar.gz"
      sha256 "45bfc5c38daa50a1124f51bb4fe911499417318c6993e336d1ec394fb4142d95"

      def install
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/dot/releases/download/v0.6.6/dot_0.6.6_Darwin_arm64.tar.gz"
      sha256 "66dd7938c3ae17865322fb5071465b96cf4802c38e50242f4331dd53b57a3cad"

      def install
        bin.install "dot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/dot/releases/download/v0.6.6/dot_0.6.6_Linux_x86_64.tar.gz"
      sha256 "42bbfc4d66483d545183f537721c11a547138c2b037eb22bbd1511a424b2474e"
      def install
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/dot/releases/download/v0.6.6/dot_0.6.6_Linux_arm64.tar.gz"
      sha256 "6aeb3dc8d2bc5cde78e9b40dd6ded025a4f6c65f9f31c55e2de01d475e5fada9"
      def install
        bin.install "dot"
      end
    end
  end

  def caveats
    <<~EOS
      dot manages configuration files through symbolic links.

      Configuration file location (XDG Base Directory):
        $XDG_CONFIG_HOME/dot/config.yaml
        or ~/.config/dot/config.yaml

      Basic usage:
        dot manage <package>    # Install package
        dot status             # Show package status
        dot unmanage <package>  # Remove package

      Documentation: https://github.com/yaklabco/dot
    EOS
  end

  test do
    system "#{bin}/dot", "--version"
    system "#{bin}/dot", "--help"
  end
end
